"""Backwards compatibility tests: current sqlite-vec reading legacy databases.

The fixture file tests/fixtures/legacy-v0.1.6.db was generated by
tests/generate_legacy_db.py using upstream sqlite-vec v0.1.6. These tests
verify that the current version can read, query, insert into, and delete from
tables created by older versions.

Ported from asg017/sqlite-vec@6e2c4c6.
"""

import os
import shutil
import sqlite3
import struct

import pytest
from conftest import get_extension_path

FIXTURE_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "legacy-v0.1.6.db")


def _f32(vals):
    return struct.pack(f"{len(vals)}f", *vals)


@pytest.fixture()
def legacy_db(tmp_path):
    """Copy the legacy fixture to a temp dir so tests can modify it."""
    db_path = str(tmp_path / "legacy.db")
    shutil.copy2(FIXTURE_PATH, db_path)
    db = sqlite3.connect(db_path)
    db.row_factory = sqlite3.Row
    db.enable_load_extension(True)
    db.load_extension(get_extension_path())
    return db


def test_legacy_select_count(legacy_db):
    count = legacy_db.execute("SELECT count(*) FROM legacy_vectors").fetchone()[0]
    assert count == 50


def test_legacy_point_query(legacy_db):
    row = legacy_db.execute(
        "SELECT rowid, emb FROM legacy_vectors WHERE rowid = 1"
    ).fetchone()
    assert row["rowid"] == 1
    vec = struct.unpack("4f", row["emb"])
    assert vec[0] == pytest.approx(1.0)


def test_legacy_knn(legacy_db):
    query = _f32([1.0, 0.0, 0.0, 0.0])
    rows = legacy_db.execute(
        "SELECT rowid, distance FROM legacy_vectors WHERE emb MATCH ? AND k = 5",
        [query],
    ).fetchall()
    assert len(rows) == 5
    assert rows[0]["rowid"] == 1
    assert rows[0]["distance"] == pytest.approx(0.0)
    for i in range(len(rows) - 1):
        assert rows[i]["distance"] <= rows[i + 1]["distance"]


def test_legacy_insert(legacy_db):
    legacy_db.execute(
        "INSERT INTO legacy_vectors(rowid, emb) VALUES (100, ?)",
        [_f32([100.0, 0.0, 0.0, 0.0])],
    )
    count = legacy_db.execute("SELECT count(*) FROM legacy_vectors").fetchone()[0]
    assert count == 51

    rows = legacy_db.execute(
        "SELECT rowid FROM legacy_vectors WHERE emb MATCH ? AND k = 1",
        [_f32([100.0, 0.0, 0.0, 0.0])],
    ).fetchall()
    assert rows[0]["rowid"] == 100


def test_legacy_delete(legacy_db):
    legacy_db.execute("DELETE FROM legacy_vectors WHERE rowid = 1")
    count = legacy_db.execute("SELECT count(*) FROM legacy_vectors").fetchone()[0]
    assert count == 49

    rows = legacy_db.execute(
        "SELECT rowid FROM legacy_vectors WHERE emb MATCH ? AND k = 5",
        [_f32([1.0, 0.0, 0.0, 0.0])],
    ).fetchall()
    assert 1 not in [r["rowid"] for r in rows]


def test_legacy_fullscan(legacy_db):
    rows = legacy_db.execute(
        "SELECT rowid FROM legacy_vectors ORDER BY rowid LIMIT 5"
    ).fetchall()
    assert [r["rowid"] for r in rows] == [1, 2, 3, 4, 5]


def test_legacy_name_conflict_table(legacy_db):
    # v0.1.6 allowed CREATE VIRTUAL TABLE emb USING vec0(emb float[4]). The
    # hidden command column named after the table would duplicate "emb".
    count = legacy_db.execute("SELECT count(*) FROM emb").fetchone()[0]
    assert count == 10

    rows = legacy_db.execute(
        "SELECT rowid, distance FROM emb WHERE emb MATCH ? AND k = 3",
        [_f32([1.0, 0.0, 0.0, 0.0])],
    ).fetchall()
    assert [(r["rowid"], r["distance"]) for r in rows] == [(1, 0.0), (2, 1.0), (3, 2.0)]

    row = legacy_db.execute("SELECT emb FROM emb WHERE rowid = 4").fetchone()
    assert row["emb"] == _f32([4.0, 0.0, 0.0, 0.0])

    # mmr_lambda is the hidden column after k when there is no command column.
    rows = legacy_db.execute(
        "SELECT rowid FROM emb WHERE emb MATCH ? AND k = 3 AND mmr_lambda = 1.0",
        [_f32([1.0, 0.0, 0.0, 0.0])],
    ).fetchall()
    assert [r["rowid"] for r in rows] == [1, 2, 3]


def test_legacy_name_conflict_insert_delete(legacy_db):
    legacy_db.execute(
        "INSERT INTO emb(rowid, emb) VALUES (100, ?)",
        [_f32([100.0, 0.0, 0.0, 0.0])],
    )
    assert legacy_db.execute("SELECT count(*) FROM emb").fetchone()[0] == 11
    rows = legacy_db.execute(
        "SELECT rowid FROM emb WHERE emb MATCH ? AND k = 1",
        [_f32([100.0, 0.0, 0.0, 0.0])],
    ).fetchall()
    assert [r["rowid"] for r in rows] == [100]

    legacy_db.execute("DELETE FROM emb WHERE rowid = 5")
    assert legacy_db.execute("SELECT count(*) FROM emb").fetchone()[0] == 10


def test_legacy_name_conflict_has_no_optimize(legacy_db):
    # "emb" names the vector column, so 'optimize' is parsed as a vector.
    with pytest.raises(sqlite3.OperationalError, match="JSON array"):
        legacy_db.execute("INSERT INTO emb(emb) VALUES ('optimize')")


def test_legacy_insert_after_chunk_deleted(legacy_db):
    # v0.1.6 declares _vector_chunks00 with "rowid PRIMARY KEY", which is not
    # an alias for _rowid_. Once its only chunk is empty, optimize deletes it,
    # so the next insert creates chunk 2, whose _rowid_ would otherwise be 1.
    legacy_db.execute("DELETE FROM legacy_vectors")
    legacy_db.execute("INSERT INTO legacy_vectors(legacy_vectors) VALUES ('optimize')")
    legacy_db.execute(
        "INSERT INTO legacy_vectors(rowid, emb) VALUES (100, ?)",
        [_f32([100.0, 0.0, 0.0, 0.0])],
    )
    rows = legacy_db.execute(
        "SELECT rowid, distance FROM legacy_vectors WHERE emb MATCH ? AND k = 1",
        [_f32([100.0, 0.0, 0.0, 0.0])],
    ).fetchall()
    assert [(r["rowid"], r["distance"]) for r in rows] == [(100, 0.0)]
    row = legacy_db.execute(
        "SELECT emb FROM legacy_vectors WHERE rowid = 100"
    ).fetchone()
    assert row["emb"] == _f32([100.0, 0.0, 0.0, 0.0])
